name: Auto Update Playlist

on:
  schedule:
    # প্রতি ৩০ মিনিট পর পর অটো চলবে
    - cron: '*/30 * * * *'
  workflow_dispatch: # আপনি চাইলে বাটন টিপেও চালাতে পারবেন

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write # গিটহাবে ফাইল লেখার পারমিশন নিশ্চিত করা
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install requests

      - name: Run update script
        run: python update_playlist.py

      - name: Commit and Push changes
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add Mayapunjo_Final.m3u
          
          # যদি ফাইলে কোনো পরিবর্তন না থাকে তবে এরর দেবে না
          git diff --quiet && git diff --staged --quiet || (git commit -m "Playlist updated with new tokens: $(date)" && git push)
